### PR TITLE
Add 'navbar_style' to params.yml

### PR DESCRIPTION
**Pull request by rluetzner**
This adds an example of where to configure the navbar style in the config. I used the default value of 'classy'.

### CODE REVIEW

**Comment by rluetzner** [comment]
I think this warrants an additional explanation/example in https://github.com/cjtheham/hugo-theme-readable 's README.md, but I'm unsure where to put it. Any ideas @cjtheham ?

**Comment by rluetzner** [comment]
Ah, before I forget: I also made sure that changing the value actually does what it's supposed to do. :sweat_smile: 

I used `default` and then `roundesque`. I nearly missed that anything happens with `default` (the animations are missing), but the difference is pretty obvious with `roundesque`, so it's in the right place. :grin:

**Comment by rluetzner** [comment]
This also updates the submodule to the latest version of hugo-theme-readable, otherwise this wouldn't work.

**Comment by cjtheham** [comment]
Looks good! Documentation wise, I would say just probably start a file like `docs/configuration.md` in the theme repo and just write a brief bit about what can be in config.yml with a link in there to the original readable.css docs for navbar styles. Thoughts?

**Comment by rluetzner** [comment]
Sounds good. I'll send you a pull request in a few minutes. :slightly_smiling_face:

**Comment by rluetzner** [comment]
Oh. Wait just a moment. I just noticed that there's a params.yml file in the same folder too. I'll check real quick if we can just put the navbar_style in there too.

**Comment by rluetzner** [comment]
Yup. That is where this should go. I actually didn't know that you can put this into a separate file, but it works as expected.

**Comment by cjtheham** [comment]
Right on, that'll probably work a bit better! Merging.

**Pull request merged**
